### ISSUE TITLE
Mismatch between package.json License and LICENSE file

### ISSUE THREAD

**Issue by m87y2k** [danny0406/Curso-Backend-Scesi#1]
### Description:
There is a discrepancy between the license specified in the package.json file and the one listed in the LICENSE file. The package.json file states the license as ISC, while the LICENSE file contains the Mozilla Public License (MPL-2.0).

### Steps to Reproduce:

- Open the package.json file.
- Check the license field, which is set to ISC.
- Open the LICENSE file.
- Notice that the license text corresponds to the MPL-2.0.

### Expected Behavior:
- The license specified in the package.json file should match the license detailed in the LICENSE file.

### Actual Behavior:

- The package.json file specifies the ISC license, while the LICENSE file details the MPL-2.0 license.

### Possible Solutions:

- Update the package.json file to reflect the MPL-2.0 license.
- Update the LICENSE file to reflect the ISC license.
- Discuss and decide on the appropriate license for the project and ensure consistency across both files.

**Comment by m87y2k** [comment]
Hola, @danny0406 
Esto lo hago solo para practicar mi redacción de PRs espero te sea de ayuda.
Saludos.

**Comment by danny0406** [comment]
Hola @dotM87 
Ya se hizo la actualización del package.json. 
Gracias, por tomarte el tiempo de revisarlo.
